### ISSUE TITLE
Especificar en el README versión mínima de Python y plataformas

### ISSUE THREAD

**Issue by L4R4** [R0land013/blue-pos#24]
Saludos. Sería bueno especificar en el README.md cuál es la versión mínima de Python requerida para ejecutar el proyecto, y las plataformas en las que se puede utilizar (Sistemas Operativos, Web, Mobile, ...)

**Comment by R0land013** [comment]
Hola @L4R4 . Lo había olvidado añadir😅. En cuanto pueda lo añado al README.md. Muchas gracias.

**Comment by R0land013** [comment]
Añadida la información al README.md en el commit c3750fb58ad2506d3fd3dcf77eac76158d982d8c
